(* type stream_error = [ `Unexpected_eof ] *)
(**)
(* type 'context t = *)
(*   ( Haha.Header.t list, *)
(*     'context Haha.Response.t, *)
(*     Pbrt.Encoder.t -> unit, *)
(*     Pbrt.Decoder.t Grpc_eio_core.Body_reader.consumer, *)
(*     stream_error, *)
(*     Haha.Error.connection_error ) *)
(*   Grpc_client_eio.Io.t *)
(**)
(* val create : *)
(*   sw:Eio.Switch.t -> *)
(*   net:_ Eio.Net.t -> *)
(*   ?debug:bool -> *)
(*   string -> *)
(*   'context t * (unit -> unit) *)
