name: windows

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - 5.1
          - 5.2
          - 5.3

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          # Only install lwt and EIO, async doesn't work on Windows reliably.
          opam-local-packages: |
            grpc.opam
            grpc-lwt.opam
            grpc-eio.opam

      - name: Install dependencies
        run: opam install ./grpc.opam ./grpc-lwt.opam ./grpc-eio.opam --deps-only --with-test

      - name: Build
        run: opam exec -- dune build lib/grpc lib/grpc-lwt lib/grpc-eio
